// GENERATED by tools/gen_hpack_vectors.py
#ifndef HPACK_VECTORS_H
#define HPACK_VECTORS_H

#define HPACK_VEC_MAX_HEADERS 6

typedef struct { const char *name, *value; } hpack_vector_header;

typedef struct {
    const char *label;
    const char *hex;
    hpack_vector_header headers[HPACK_VEC_MAX_HEADERS];
    int header_count;
} hpack_vector_step;

typedef struct {
    const char *label;
    unsigned table_size;
    const hpack_vector_step *steps;
    int step_count;
} hpack_vector_seq;

extern const hpack_vector_seq hpack_vectors[];
extern const int hpack_vectors_count;

#endif
