// GENERATED by tools/gen_nacl_vectors.py
#ifndef NACL_VECTORS_H
#define NACL_VECTORS_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    size_t         mlen;
    const uint8_t *sk_a;     // our private key (32)
    const uint8_t *pk_b;     // their public key (32)
    const uint8_t *shared;   // expected crypto_box_beforenm output (32)
    const uint8_t *nonce;    // 24
    const uint8_t *msg;      // mlen
    const uint8_t *sealed;   // 16-byte tag followed by mlen ciphertext bytes
} nacl_vector;

extern const nacl_vector nacl_vectors[];
extern const int nacl_vectors_count;

#endif
