#!/usr/bin/env python3
"""Extract the HPACK examples from RFC 7541 Appendix C into a C test table.

Each C.N group shares one decoder (the dynamic table carries across requests),
which is exactly the state-dependent behaviour worth testing. C.5 and C.6 run
with a 256-byte table so eviction actually happens.
"""
import re, sys, urllib.request

text = urllib.request.urlopen("https://www.rfc-editor.org/rfc/rfc7541.txt",
                              timeout=30).read().decode("utf-8", "replace")

# Drop page furniture so dumps that straddle a page break stay contiguous.
text = "\n".join(l for l in text.splitlines()
                 if not l.startswith("Peon & Ruellan")
                 and not l.startswith("RFC 7541")
                 and "\f" not in l)
lines = text.splitlines()

# Locate every "C.x.y.  Title" heading in the appendix.
heads = [(i, m.group(1)) for i, l in enumerate(lines)
         if (m := re.match(r"^(C\.\d+\.\d+)\.\s+\S", l))]
if not heads:
    sys.exit("no appendix C sections found")

def block_after(start, end, marker, parser):
    i = start
    while i < end and marker not in lines[i]:
        i += 1
    if i >= end:
        return None
    i += 1
    while i < end and not lines[i].strip():
        i += 1
    out = []
    while i < end:
        v = parser(lines[i])
        if v is None:
            break
        out.append(v)
        i += 1
    return out

def parse_header(l):
    s = l.strip()
    if not s or ": " not in s and not s.endswith(":"):
        return None
    if s.startswith("Hex dump") or s.startswith("Decoding"):
        return None
    name, _, value = s.partition(": ")
    if not re.match(r"^[:a-z0-9\-]+$", name):
        return None
    return (name, value)

def parse_hex(l):
    part = l.split("|")[0].strip()
    if not part or not re.fullmatch(r"[0-9a-f ]+", part):
        return None
    return part.replace(" ", "")

cases = []
for n, (idx, name) in enumerate(heads):
    end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
    hdrs = block_after(idx, end, "Header list to encode", parse_header)
    hexd = block_after(idx, end, "Hex dump of encoded data", parse_hex)
    if not hdrs or not hexd:
        continue
    cases.append((name, "".join(hexd), hdrs))

# C.2.x examples each start from an empty table; C.3..C.6 are sequences.
def group_of(name):
    major = name.split(".")[1]
    return name if major == "2" else "C." + major

def table_size(name):
    return 256 if name.split(".")[1] in ("5", "6") else 4096

groups, order = {}, []
for name, hexs, hdrs in cases:
    g = group_of(name)
    if g not in groups:
        groups[g] = []
        order.append(g)
    groups[g].append((name, hexs, hdrs))

out = ["// GENERATED by tools/gen_hpack_vectors.py from RFC 7541 Appendix C.",
       "#include \"hpack_vectors.h\"", ""]
seq_names = []
for g in order:
    ident = "seq_" + g.replace(".", "_").lower()
    seq_names.append((g, ident, table_size(groups[g][0][0])))
    out.append(f"static const hpack_vector_step {ident}_steps[] = {{")
    for name, hexs, hdrs in groups[g]:
        out.append(f'    {{ "{name}",')
        out.append(f'      "{hexs}",')
        out.append("      {")
        for hn, hv in hdrs:
            hv = hv.replace('\\', '\\\\').replace('"', '\\"')
            out.append(f'          {{ "{hn}", "{hv}" }},')
        out.append("      },")
        out.append(f"      {len(hdrs)} }},")
    out.append("};")
    out.append("")

out.append("const hpack_vector_seq hpack_vectors[] = {")
for g, ident, tsize in seq_names:
    out.append(f'    {{ "{g}", {tsize}, {ident}_steps, '
               f"sizeof({ident}_steps)/sizeof({ident}_steps[0]) }},")
out.append("};")
out.append(f"const int hpack_vectors_count = {len(seq_names)};")

open("host/hpack_vectors.c", "w").write("\n".join(out) + "\n")

maxh = max(len(h) for _, _, h in cases)
open("host/hpack_vectors.h", "w").write(f"""\
// GENERATED by tools/gen_hpack_vectors.py
#ifndef HPACK_VECTORS_H
#define HPACK_VECTORS_H

#define HPACK_VEC_MAX_HEADERS {maxh}

typedef struct {{ const char *name, *value; }} hpack_vector_header;

typedef struct {{
    const char *label;
    const char *hex;
    hpack_vector_header headers[HPACK_VEC_MAX_HEADERS];
    int header_count;
}} hpack_vector_step;

typedef struct {{
    const char *label;
    unsigned table_size;
    const hpack_vector_step *steps;
    int step_count;
}} hpack_vector_seq;

extern const hpack_vector_seq hpack_vectors[];
extern const int hpack_vectors_count;

#endif
""")

print(f"extracted {len(cases)} examples in {len(seq_names)} sequences, "
      f"max {maxh} headers per example")
for g, _, ts in seq_names:
    print(f"  {g:8s} table={ts:4d}  steps={len(groups[g])}")
