#!/usr/bin/env python3
"""Generate NaCl box/secretbox test vectors using libsodium (via PyNaCl), so
our implementation is checked against the reference rather than against
numbers typed out of a paper.

Message lengths straddle 32 bytes on purpose: NaCl reserves the first 32
bytes of the keystream for the Poly1305 key, and that offset is the easiest
place to get a hand-written implementation wrong.

Run with:  /tmp/tsesp-venv/bin/python tools/gen_nacl_vectors.py
"""
import os
import nacl.bindings as b

LENGTHS = [0, 1, 15, 16, 31, 32, 33, 63, 64, 65, 127, 200]

def c_bytes(name, data):
    if not data:
        return f"static const uint8_t {name}[1] = {{ 0 }};   /* empty */"
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + " ".join(f"0x{x:02x}," for x in data[i:i + 12]))
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};"

out = ["// GENERATED by tools/gen_nacl_vectors.py against libsodium (PyNaCl).",
       "// Do not edit by hand; re-run the generator instead.",
       '#include "nacl_vectors.h"', ""]
cases = []

# Deterministic input so regenerating produces the same file.
seed = 0
def det(n):
    global seed
    data = bytearray()
    while len(data) < n:
        seed = (seed * 6364136223846793005 + 1442695040888963407) & (2**64 - 1)
        data += seed.to_bytes(8, "little")
    return bytes(data[:n])

for idx, mlen in enumerate(LENGTHS):
    sk_a = det(32); sk_b = det(32)
    # PyNaCl clamps internally for scalarmult_base; match what we store.
    pk_a = b.crypto_scalarmult_base(sk_a)
    pk_b = b.crypto_scalarmult_base(sk_b)
    shared = b.crypto_box_beforenm(pk_b, sk_a)
    shared_rev = b.crypto_box_beforenm(pk_a, sk_b)
    assert shared == shared_rev, "beforenm must be symmetric"
    nonce = det(24)
    msg = det(mlen)
    sealed = b.crypto_secretbox(msg, nonce, shared)   # tag || ciphertext
    assert len(sealed) == mlen + 16

    for nm, val in (("sk_a", sk_a), ("pk_b", pk_b), ("shared", shared),
                    ("nonce", nonce), ("msg", msg), ("sealed", sealed)):
        out.append(c_bytes(f"v{idx}_{nm}", val))
    out.append("")
    cases.append((idx, mlen))

out.append("const nacl_vector nacl_vectors[] = {")
for idx, mlen in cases:
    out.append(f"    {{ {mlen}, v{idx}_sk_a, v{idx}_pk_b, v{idx}_shared, "
               f"v{idx}_nonce, v{idx}_msg, v{idx}_sealed }},")
out.append("};")
out.append(f"const int nacl_vectors_count = {len(cases)};")

os.makedirs("host", exist_ok=True)
open("host/nacl_vectors.c", "w").write("\n".join(out) + "\n")
open("host/nacl_vectors.h", "w").write("""\
// GENERATED by tools/gen_nacl_vectors.py
#ifndef NACL_VECTORS_H
#define NACL_VECTORS_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    size_t         mlen;
    const uint8_t *sk_a;     // our private key (32)
    const uint8_t *pk_b;     // their public key (32)
    const uint8_t *shared;   // expected crypto_box_beforenm output (32)
    const uint8_t *nonce;    // 24
    const uint8_t *msg;      // mlen
    const uint8_t *sealed;   // 16-byte tag followed by mlen ciphertext bytes
} nacl_vector;

extern const nacl_vector nacl_vectors[];
extern const int nacl_vectors_count;

#endif
""")
print(f"{len(cases)} vektör üretildi, mesaj uzunlukları: {LENGTHS}")
