#!/usr/bin/env python3
"""Generate HPACK static + Huffman tables (src/hpack_tables.c) straight from
RFC 7541, so no table is ever transcribed by hand."""
import re, sys, urllib.request

RFC = "https://www.rfc-editor.org/rfc/rfc7541.txt"
text = urllib.request.urlopen(RFC, timeout=30).read().decode("utf-8", "replace")

# ---- Appendix A: static table ("| 1  | :authority |    |") ----------------
static = {}
for m in re.finditer(r"^\s*\|\s*(\d+)\s*\|\s*([!-~]+)\s*\|([^|]*)\|\s*$", text, re.M):
    idx, name, value = int(m.group(1)), m.group(2), m.group(3).strip()
    if 1 <= idx <= 61 and name.strip():
        static.setdefault(idx, (name, value))
missing = [i for i in range(1, 62) if i not in static]
if missing:
    sys.exit(f"static table incomplete, missing {missing}")

# ---- Appendix B: Huffman code -------------------------------------------
# Rows are either "( 27)  |1111...  ffffff7  [28]" or, for printable
# characters, prefixed with the character: "'!' ( 33)  |11111110|00 ...".
huff = {}
for m in re.finditer(r"\(\s*(\d+)\)\s*\|[01|]+\s+([0-9a-f]+)\s+\[\s*(\d+)\s*\]", text):
    huff[int(m.group(1))] = (int(m.group(2), 16), int(m.group(3)))
missing = [i for i in range(257) if i not in huff]
if missing:
    sys.exit(f"huffman table incomplete, missing {len(missing)} symbols")

# ---- Verify the code is canonical ---------------------------------------
# The decoder walks bit by bit and relies on codes of each length being
# consecutive, with first_code[L] == (first_code[L-1] + count[L-1]) << 1.
order = sorted(huff.items(), key=lambda kv: (kv[1][1], kv[1][0]))
counts = {}
for _, (_, bits) in order:
    counts[bits] = counts.get(bits, 0) + 1
maxlen = max(counts)

first_code, first_index = {}, {}
code = idx = 0
for L in range(1, maxlen + 1):
    code = (code + counts.get(L - 1, 0)) << 1
    first_code[L] = code
    first_index[L] = idx
    idx += counts.get(L, 0)

for pos, (sym, (code, bits)) in enumerate(order):
    want = first_code[bits] + (pos - first_index[bits])
    if want != code:
        sys.exit(f"HUFFMAN TABLE IS NOT CANONICAL at symbol {sym}: {code:x} != {want:x}")

symbols = [sym for sym, _ in order]

# ---- Emit C -------------------------------------------------------------
out = []
w = out.append
w("// GENERATED by tools/gen_hpack.py from RFC 7541. Do not edit by hand.")
w('#include "hpack.h"')
w("")
w("const hpack_static_entry hpack_static_table[HPACK_STATIC_COUNT] = {")
for i in range(1, 62):
    n, v = static[i]
    w(f'    {{ "{n}", "{v}" }},')
w("};")
w("")
w("// Canonical Huffman decoding tables, indexed by code length.")
w("const uint8_t hpack_huff_bits[257] = {")
for i in range(0, 257, 16):
    w("    " + " ".join(f"{huff[s][1]:3d}," for s in range(i, min(i + 16, 257))))
w("};")
w("const uint32_t hpack_huff_code[257] = {")
for i in range(0, 257, 8):
    w("    " + " ".join(f"0x{huff[s][0]:08x}," for s in range(i, min(i + 8, 257))))
w("};")
w(f"const uint32_t hpack_huff_first_code[{maxlen + 1}] = {{")
w("    " + " ".join(f"0x{first_code.get(L, 0):08x}," for L in range(maxlen + 1)))
w("};")
w(f"const uint16_t hpack_huff_first_index[{maxlen + 1}] = {{")
w("    " + " ".join(f"{first_index.get(L, 0)}," for L in range(maxlen + 1)))
w("};")
w(f"const uint16_t hpack_huff_count[{maxlen + 1}] = {{")
w("    " + " ".join(f"{counts.get(L, 0)}," for L in range(maxlen + 1)))
w("};")
w("const uint16_t hpack_huff_symbol[257] = {")
for i in range(0, 257, 16):
    w("    " + " ".join(f"{s:3d}," for s in symbols[i:i + 16]))
w("};")

open("src/hpack_tables.c", "w").write("\n".join(out) + "\n")
print(f"static table : 61 entries")
print(f"huffman      : 257 symbols, code lengths {min(counts)}..{maxlen}, canonical verified")
print(f"HPACK_HUFF_MAX_BITS should be {maxlen}")
print("wrote src/hpack_tables.c")
